spring.application.name=backend
# Server Configuration
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://31uysq4XhrPamv5.root:xvUQW9zY2KWOZRob@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/studygroup?sslMode=VERIFY_IDENTITY
spring.datasource.username=31uysq4XhrPamv5.root
spring.datasource.password=xvUQW9zY2KWOZRob
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=d7e7b6189b127b29dd9040744487ba69648c8b1a66bb6dd07c3c4b26e372825e
jwt.expiration=86400000

# CORS
cors.allowed-origins=https://edunion.onrender.com

# SMTP Configuration
 spring.mail.host=smtp.sendgrid.net
 spring.mail.port=587
 spring.mail.username=apikey
 spring.mail.password=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
 spring.mail.properties.mail.smtp.auth=true
 spring.mail.properties.mail.smtp.starttls.enable=true
 spring.mail.properties.mail.smtp.starttls.required=true

# Cloudinary Configuration
cloudinary.cloud-name=dfyvwp2dx
cloudinary.api-key=981887971326494
cloudinary.api-secret=DNlypwPJqnJ6ZS2h3L693Euf77A

# File upload configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
